# Generated by Django 4.2.5 on 2023-10-28 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('confirm_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirm_orders', to='profiles.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.customer')),
                ('deliver_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliver_orders', to='profiles.employee')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.laptop')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderdetails')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.employee')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
                ('return_details', models.ManyToManyField(through='orders.ReturnDetails', to='orders.orderdetails')),
            ],
        ),
        migrations.AddField(
            model_name='returndetails',
            name='return_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.returnform'),
        ),
        migrations.AddField(
            model_name='order',
            name='laptops',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderDetails', to='controls.laptop'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='orders.state'),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='orderdetails',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='CK_ORDER_PRICE'),
        ),
    ]
