# Generated by Django 4.2.5 on 2023-10-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.employee')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LaptopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='img/default.jpg', upload_to='products/')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cart_details', models.ManyToManyField(related_name='cart_details', through='controls.CartDetails', to='profiles.customer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('laptop_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.laptopmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('disk', models.CharField(max_length=200)),
                ('vga', models.CharField(max_length=200)),
                ('battery', models.FloatField()),
                ('screensize', models.FloatField()),
                ('resolution', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
            ],
            options={
                'unique_together': {('os', 'ram', 'cpu', 'disk', 'vga', 'battery', 'screensize', 'resolution', 'weight')},
            },
        ),
        migrations.CreateModel(
            name='ReservationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.employee')),
                ('reservation_details', models.ManyToManyField(blank=True, through='controls.ReservationDetails', to='controls.laptopmodel')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.supplier')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='reservation_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.reservationform'),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('specifications', models.ManyToManyField(related_name='manufacturers', through='controls.LaptopModel', to='controls.specification')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.employee')),
            ],
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.manufacturer'),
        ),
        migrations.AddField(
            model_name='laptopmodel',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.specification'),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False)),
                ('importation_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.importationform')),
                ('laptop_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.laptopmodel')),
                ('liquidation_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controls.liquidationform')),
            ],
        ),
        migrations.AddField(
            model_name='importationform',
            name='importation_details',
            field=models.ManyToManyField(through='controls.ImportationDetails', to='controls.reservationdetails'),
        ),
        migrations.AddField(
            model_name='importationform',
            name='reservation_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='controls.reservationform'),
        ),
        migrations.AddField(
            model_name='importationdetails',
            name='importation_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.importationform'),
        ),
        migrations.AddField(
            model_name='importationdetails',
            name='reservations_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controls.reservationdetails'),
        ),
        migrations.AddField(
            model_name='cartdetails',
            name='laptop_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controls.laptopmodel'),
        ),
        migrations.AddConstraint(
            model_name='reservationdetails',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='CK_RESERVATION_DETAILS_QUANTITY'),
        ),
        migrations.AddConstraint(
            model_name='laptopmodel',
            constraint=models.CheckConstraint(check=models.Q(('price__gt', 0)), name='CK_MODEL_PRICE'),
        ),
        migrations.AddConstraint(
            model_name='laptopmodel',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='CK_MODEL_QUANTITY'),
        ),
        migrations.AddConstraint(
            model_name='importationdetails',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='CK_IMPORTATION_DETAILS_QUANTITY'),
        ),
        migrations.AddConstraint(
            model_name='cartdetails',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='CK_CART_QUANTITY'),
        ),
    ]
